spring:
  application:
    name: f5-template
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/f5lock?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&rewriteBatchedStatements=true
    username: user
    password: password
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        generate_statistics: false
  jmx:
    enabled: true
  redis:
    host: localhost
    port: 6379

logging:
  config: classpath:log4j2/log4j2-local.xml
  level:
    ROOT: INFO
    kr:
      flab: DEBUG
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        security: DEBUG

springfox:
  documentation:
    swagger-ui:
      enabled: true

server:
  port: 8080
  shutdown: graceful
